subcategory_map = {

    # ===== A. Literature, the humanities, including philosophy and the arts =====
    "Writing as a concept, for example as an occupation, as an art form, etc.": "Writing as a concept",
    "Writers, authors or translators of literary, artistic or philosophical works": "Writers, authors or translators",
    "The Book / Books as a concept, for example in references like 'books are an extension of the imagination'": "Books as a concept",
    "Specific books, like the Divine Comedy": "Specific books",
    "Other specific literary works, like poems, essays, plays, conferences, manifestos, etc.": "Other literary works",
    "Literary concepts, like the art of storytelling, or poetry as an art": "Literary concepts",
    "Literary genres, including realism, detective fiction, fantastic literature, poetry, essays, chronicles, book or film review, etc.": "Literary genres",
    "Literary techniques like the use of hypallage, anaphora, allegory, symbolism, foreshadowing, stream of consciousness or metonymy": "Literary techniques",
    "Translation as a concept, as in discussions of different ways of translating, from more literal to more liberal, the role of the translator": "Translation as a concept",
    "Translations, meaning specific instances, like Baudelaire's translations of Edgar Allan Poe": "Translations",
    "Art, artistic styles and concepts, like Italian art, Japanese painting or realism in art": "Artistic styles and concepts",
    "Art and specific artworks, such as Xul Solar's paintings": "Specific artworks",
    "Music as a concept, including related ideas such as harmony": "Music as a concept",
    "Musical genres, like jazz, the tango, the milonga or the blues": "Musical genres",
    "Music and musical works, like 'La Cumparsita'": "Musical works",
    "Film as a concept, that is, film as an art form, and discussions on dubbing vs. subtitles, or silent movies vs. talkies.": "Film as a concept",
    "Films, like Charlie Chaplin's City Lights": "Films",
    "Film directors and actors, like King Vidor or Joseph von Sternberg": "Film directors and actors",
    "Language in general, including linguistics and philology.": "Language in general",
    "Languages, like Spanish, French or German": "Languages",
    "Literary theory or techniques, including narrative techniques like hypallage or metonymy": "Literary theory or techniques",
    "Literatures of the world, like French, English or Argentine literature": "World literatures",
    "Awards and prizes in general, for example in references like 'the real prize is thinking and reading'": "Awards and prizes",

    # ===== B. Borges’s work =====
    "Borges's Books": "Borges's Books",
    "Borges's Stories": "Borges's Stories",
    "Borges's Poems": "Borges's Poems",
    "Essays": "Essays",
    "Borges's Book or film reviews": "Borges's Book or film reviews",
    "Borges's Conferences or classes, including both transcripts and published versions": "Borges's Conferences or classes",
    "Borges's Translations": "Borges's Translations",
    "Borges's Collaborations including those with Adolfo Bioy Casares, María Esther Vázquez and Alicia Jurado": "Borges's Collaborations",
    "Borges's Letters, including published collections and unpublished ones": "Borges's Letters",

    # ===== C. History, religion, politics and public life =====
    "Historical figures, for example Napoleon or Julius Cesar": "Historical figures",
    "Religions and religious studies, including specific concepts like Judaism, Kabbalah, Christianity, Buddhism and Islam": "Religions and religious studies",
    "Figures related to current affairs (politicians, artists, athletes)": "Current figures",
    "Historical periods like the Middle Ages, the Inter-war years, or 19th century": "Historical periods",
    "Historical events, including battles, revolutions, wars, invasions, etc.": "Historical events",
    "Current affairs events, like the Nobel Prize being awarded to Gabriel García Marquez, the Falklands War, or the landing on the Moon": "Current events",
    "Sports and popular culture as concepts, like football": "Sports (concept)",
    "Sports and popular culture specific instances, like the 1978 Football World Cup": "Sports (events)",
    "Historical Concepts and Theories, including The Role of Heroes/Great Individuals, Historical Memory & Amnesia, The Construction of National Myths, Historical Recurrence (Eternal Return applied to history)": "Historical concepts",
    "Political Concepts & Ideologies including Anarchism, Liberalism, Fascism, Communism, Nationalism & Patriotism, Totalitarianism vs. Individual Liberty, Utopia and Dystopia, etc": "Political concepts",
    "Religious & Theological Concepts, like Heresy, Orthodoxy, Mysticism, Faith, Sin, Redemption, Grace, Sacred and Profane, Kaballah": "Religious & Theological Concepts",
    "Mythological & Folklore Concepts, like Archetypes, Myth as collective memory, etc.": "Mythological & Folklore Concepts",
    "Socio-cultural concepts like traditions vs modernity, cultural identity, populism and mass media, civilization vs. barbarism": "Socio-cultural concepts",
    "War and conflicts, including War Theory, Strategy, the psychology of enmity": "War and conflicts",
    "Time and temporality in History, including Nostalgia, Ruins and Decay": "Time and temporality",
    "Ethics and Moral Philosophy, including Justice (Divine or social), courage, betrayal and honor, moral relativism, free will": "Ethics and Moral Philosophy",

    # ===== D. Places =====
    "Countries": "Countries",
    "Cities": "Cities",
    "Neighborhoods or streets": "Neighborhoods or streets",
    "Mountains": "Mountains",
    "Rivers": "Rivers",
    "Famous buildings": "Famous buildings",
    "Regions (ex: Europe, Northern Italy, etc)": "Regions",
    "Libraries (real ones, including Borges's father library, Miguel Cané library, etc.)": "Libraries",
    "Other institutions, including newspapers, etc.": "Institutions",
    "Other physical places, not included in the above": "Other physical places",

    # ===== E. Biography (Borges’s life) =====
    "Friends and acquaintances": "Friends and acquaintances",
    "Family members": "Family members",
    "Places or cities where Borges lived": "Places or cities where Borges lived",
    "Places or cities that Borges visited": "Places or cities that Borges visited",
    "Life events, including travels, professional appointments, personal experiences, historical events impacting him, conferences given, books published, marriage, etc.": "Life events",

    # ===== F. Recurrent symbols and metaphors =====
    "Mirrors": "Mirrors",
    "Encyclopaedias": "Encyclopaedias",
    "Labyrinths": "Labyrinths",
    "Tigers": "Tigers",
    "Swords and daggers": "Swords and daggers",
    "Memory": "Memory",
    "Time and Eternity": "Time and Eternity",
    "The infinite": "The infinite",
    "The double": "The Double",
    "Writing, including the act of writing, the writer's profession or skills": "Writing",
    "Physical books, that is, books considered as physical objects, as distinct from titles": "Physical books",
    "Gardens": "Gardens",
    "Coins": "Coins",
    "Dreams": "Dreams",
    "Circularity": "Circularity",
    "Maps": "Maps",
    "Colors": "Colors",
    "The past, childhood and memory places": "The past",

    # ===== G. Core philosophical or conceptual themes =====
    "Writing as an occupation, writing habits, etc.": "Writing (occupation)",
    "Idealism vs. Realism": "Idealism vs. Realism",
    "The Nature of Time (Circular, Branching, Subjective)": "Nature of Time",
    "Identity & The Self (The Double is a symbol for this)": "Identity & Self",
    "Reality vs. Illusion / Dream": "Reality vs. Illusion",
    "The Nature of Infinity": "Infinity (concept)",
    "The Paradox": "Paradox",
    "The Nature of Language & Naming": "Language & Naming",
    "Memory & Forgetting": "Memory & Forgetting",
    "Fate, Chance, & Free Will": "Fate & Free Will",
    "The Search for Meaning / Order": "Meaning & Order",
    "The Author/Reader relationship": "Author/Reader",
    "The Nature of Knowledge & Encyclopedias / Libraries (the concept)": "Knowledge & Encyclopedias",

    # ===== H. Science and mathematics =====
    "Mathematicians like Georg Cantor, Bertrand Russell, Zeno, Pythagoras": "Mathematicians",
    "Scientists & Philosophers of Science (Einstein, Newton, Descartes, William James)": "Scientists & Philosophers",
    "Mathematical concepts like infinity, paradoxes like the Russell paradox or the Zeno paradox, the fourth dimension, combinatorics and probability": "Mathematical concepts",

    # ===== I. Literary Fiction and Fictional Constructs =====
    "Fictional characters and persons including human characters (like Erik Lönnot), authors (like Bustos Domecq) or historical figures reimagined, like Cervantes in Pierre Menard": "Fictional characters",
    "Fictional places and geographies, including fictional cities like Uqbar, fictional architectures like the Library of Babel and fictional cosmologies like Tlön's planetary system.": "Fictional places",
    "Fictional books and texts, like the First Encyclopaedia of Tlön, or The approach to Al-Mutasim": "Fictional books and texts",
    "Fictional authors like Herbert Quain or Mir Bahadur Ali": "Fictional authors",
    "Fictional paratexts and objects like apocryphal footnotes": "Fictional paratexts and objects",
    "Fictional philosophies and systems like Tlön's idealism or Babylon's Lottery rules": "Fictional philosophies and systems",
}
